### ISSUE TITLE
Moving the mouse over the left hand side generates exception.

### ISSUE THREAD

**Issue by jkbbwr** [Hexworks/zircon#21]
Using a tiled window manager that allows floating windows, when moving the mouse beyond the left hand side it generates the following exception

```
AWT-EventQueue-0] ERROR org.codetome.zircon.internal.terminal.swing.SwingTerminal$listener$1 - position for mouse event 'java.lang.IllegalArgumentException: A position must have a column and a row number which is greater than or equal to 0!' was out of bounds. It is dropped.
java.lang.IllegalArgumentException: A position must have a column and a row number which is greater than or equal to 0!
	at org.codetome.zircon.api.Position.<init>(Position.kt:14)
	at org.codetome.zircon.api.Position$Companion.of(Position.kt:181)
	at org.codetome.zircon.internal.terminal.swing.TerminalMouseListener.addActionToKeyQueue(TerminalMouseListener.kt:77)
	at org.codetome.zircon.internal.terminal.swing.TerminalMouseListener.mouseExited(TerminalMouseListener.kt:53)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by adam-arold** [comment]
Nice catch! I'll look into it!
