### ISSUE TITLE
Adding a component to a container which has no font before attaching that container to a Screen leads to font error.

### ISSUE THREAD

**Issue by adam-arold** [Hexworks/zircon#47]
Example:

```
Exception in thread "main" kotlin.NotImplementedError: An operation is not implemented.
	at org.codetome.zircon.internal.font.impl.FontSettings$NO_FONT$1.getWidth(FontSettings.kt:18)
	at org.codetome.zircon.api.font.Font$DefaultImpls.getSize(Font.kt:45)
	at org.codetome.zircon.internal.font.impl.FontSettings$NO_FONT$1.getSize(FontSettings.kt:11)
	at org.codetome.zircon.internal.component.impl.DefaultContainer.addComponent(DefaultContainer.kt:46)
	at org.codetome.zircon.examples.interactive.ShootingExample.main(ShootingExample.java:91)
```

This is because the container like a `Panel` does not have a `Font` by default. The reason for this is that if we would have had a default font with any size it would have lead to an error if the user would have used a different sized font as our default.
Since the user sets the font for the whole `Screen` we can't add a component to another container component until a `Font` is set for it.

This needs to be clarified in the error message above!

**Comment by coldwarrl** [comment]
could you give me an example to reproduce:

For instance,
```
val panel = PanelBuilder.newBuilder()
                .size(Size.of(5,5))
                .build()

        panel.addComponent(LabelBuilder.newBuilder()
                .text("foo")
                .build())
```

seems to work

**Comment by adam-arold** [comment]
This is fixed in the new version.
